# Setup
title:               Ejercicios de Javascript
tagline:             #''
description:         #''
url:                 https://araceliponce.github.io
baseurl:             '/ejercicios-avanzados'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              #
  url:               #
  email:             #

# Gems
plugins:
  - jekyll-paginate

# Custom vars
google_analytics_id: #UA-XXXX-Y
